name: Ansible 5.4 Full

on:
  push:
    paths:
      - ".github/workflows/ansible_v5.4_full_doc.yml"

env:
  ANSIBLE_VERSION: 5.4
  DOC_PATH: docs/ansible/v5.4/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependency
        run: pip install -r requirements.txt

      - name: Install Ansible ${{ env.ANSIBLE_VERSION }}
        run: pip install ansible==${{ env.ANSIBLE_VERSION }}

      - name: Generate Doc
        run: |
          mkdir -p ${{ env.DOC_PATH }}
          python gen_ansible_doc.py ${{ env.DOC_PATH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          title: Doc for Ansible v${{ env.ANSIBLE_VERSION }}
          branch: doc/v${{ env.ANSIBLE_VERSION }}/full
          add-paths: |
            ${{ env.DOC_PATH }}
