name: Generate Ansible Moudle Documentation

# version: v18

on:
  push:
    paths:
      - '.github/workflows/ansible_v5.3_amazon_aws.yml'

env:
  ANSIBLE_COLLECTION: amazon.aws
  ANSIBLE_VERSION: 5.3
  DOC_PATH: docs/ansible/v5.3/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependency
        run: pip install -r requirements.txt

      - name: Install Ansible ${{ env.ANSIBLE_VERSION }}
        run: pip install ansible==${{ env.ANSIBLE_VERSION }}

      - name: Generate Doc
        run: |
          mkdir -p ${{ env.DOC_PATH }}
          python gen_ansible_doc.py ${{ env.DOC_PATH }} --collection ${{ env.ANSIBLE_COLLECTION }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          add-paths: |
            ${{ env.DOC_PATH }}

